const header = document.querySelector('.header');
const searchBar = document.querySelector('.searchBar');
const houseIcons = document.querySelectorAll('.house_icon');
const headerTextButton = document.querySelector('.header_text__button');
const headerTextP = document.querySelector('.header_text_p');
const trendingMovies = document.querySelector('.popular_movies');
const popularMoviesCards = document.querySelector('#popular_movies__cards');
const movieInfoPage = document.querySelector('.movie_info__page');
const movieHeader = document.querySelector('.movie_header');
const movieInfoContainer = document.querySelector('.movie_info__container');
const movieTitle = document.querySelector('.movie_info h1');
const movieInfoText = document.querySelectorAll('.movie_info__text p');
const movieIframe = document.querySelector('.movie_info__container iframe');
const movieGenres = document.querySelector('.movie_genres');
const movieGenresCards = document.querySelector('#movie_genres__cards');
const movieOverView = document.querySelector(".movie_overview")
const moviePageContainer = document.querySelector("#movie_page_container")
const trendingSeries = document.querySelector('.popular_series');
const popularSeriesCards = document.querySelector('#popular_series__cards');
const pinkButtons = document.querySelectorAll('#pink_buttons');
const popularMoviesButton = document.querySelector("#popular_movies_button")
const popularSeriesButton = document.querySelector("#popular_series_button")
const backButtonMovie = document.querySelector("#back_btn_movie")
const backButtonCategory = document.querySelector("#back_btn_category")
const searchButton = document.querySelector(".search_btn")
const categoryPage = document.querySelector('.category_page');
const categoryHeader = document.querySelector('.category_header');
const categoryInfoContainer = document.querySelector('.category_info__container');
const categoryTitle = document.querySelector('.category_info__title h1');
const categoryGenre = document.querySelector('.category_genre');
const searchFormCategory = document.querySelector('#searchForm_category');
const searchInputCategory = document.querySelector('#searchForm_category input');
const searchButtonCategory = document.querySelector('#search_button_category');
const categoryCardsContainer = document.querySelector('#category_cards__container');
const categoryCards = document.querySelector('#category_cards');
const inputMain = document.querySelector("#searchForm input")
